### ISSUE TITLE
Add: Import via URL

### ISSUE THREAD

**Issue by modl21** [bitcointelevision/BitcoinTV.com#1]
Import from URL is a native peertube feature and appears to be disabled on this instance. Would make importing youtube videos much easier.

![image](https://user-images.githubusercontent.com/50266466/130528016-5ea4658e-1efb-4680-92c4-11b7139632ef.png)

**Comment by wiz** [comment]
ok try now
<img width="1010" alt="Screen Shot 2021-08-25 at 1 08 54" src="https://user-images.githubusercontent.com/232186/130651559-0cef9e4b-9657-4727-872e-46b82fdfe582.png">
